apiVersion: v1
kind: Service
metadata:
  name: mysql-db-service # Stable DNS name PHP app will use
  namespace: guestbook-ha
spec:
  selector:
    app: mysql-db # Selects the MySQL pod
  ports:
    - port: 3306
      targetPort: 3306