apiVersion: v1
kind: Service
metadata:
  name: mysql-db-headless
  namespace: guestbook-ha
spec:
  clusterIP: None # Headless service
  selector:
    app: mysql-db # Selects the MySQL pod
  ports:
    - port: 3306
      targetPort: 3306